version: "3.8"

services:
  # Giao diá»‡n Frontend Production
  frontend:
    image: ${DOCKERHUB_USERNAME}/miniblog-frontend:latest
    networks:
      - blog-network

  # Backend API Server
  api:
    image: ${DOCKERHUB_USERNAME}/miniblog-backend:latest
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_USER=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-root}
      - DB_NAME=${POSTGRES_DB:-blog_db}
      - DB_PORT=5432
      - JWT_SECRET=${JWT_SECRET:-supersecretkey}
      - JWT_EXPIRES_IN=1h
      - BCRYPT_SALT_ROUNDS=10
    depends_on:
      - db
    networks:
      - blog-network

  # Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_DB=${POSTGRES_DB:-blog_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - blog-network

  # NGINX API Gateway (Reverse Proxy)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - api
    networks:
      - blog-network

volumes:
  pgdata:

networks:
  blog-network:
