version: "3.8"

services:
  # Service 1: Backend API
  api:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=blog_db
      - DB_PORT=5432
      - JWT_SECRET=supersecretkey
      - JWT_EXPIRES_IN=1h
      - BCRYPT_SALT_ROUNDS=10
    depends_on:
      - db
    networks:
      - blog-network

  # Service 2: Database PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=blog_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - blog-network

  # Service 3: Frontend (React + Vite)
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000 # Frontend gọi Backend qua localhost của máy Host (vì chạy ở browser)
    depends_on:
      - api
    volumes:
      - ./frontend/src:/app/src # Hot Reload: map code local vào container
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.js:/app/vite.config.js
    networks:
      - blog-network

volumes:
  pgdata:

networks:
  blog-network:
