version: "3.8"

services:
  # Service 1: Backend API
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=db # Quan trọng: Tên service database bên dưới
      - DB_USER=postgres
      - DB_PASSWORD=root # Mật khẩu cho DB Docker
      - DB_NAME=blog_db
      - DB_PORT=5432
      - JWT_SECRET=supersecretkey
      - JWT_EXPIRES_IN=1h
      - BCRYPT_SALT_ROUNDS=10
    depends_on:
      - db
    networks:
      - blog-network

  # Service 2: Database PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=blog_db
    ports:
      - "5433:5432" # Map port 5433 (host) -> 5432 (container) để tránh trùng Postgres local
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql # Tự động chạy script tạo bảng
    networks:
      - blog-network

volumes:
  pgdata: # Volume để lưu dữ liệu bền vững

networks:
  blog-network:
